### ISSUE TITLE
ttl template changes

### ISSUE THREAD

**Issue by kmexter** [emo-bon/emobon-ontology#4]
I know this is probably not the place to raise this, but was not sure where

The ttl template may need updating
1) the pigments and phaopigments are now singular not lists -> think we changed this in the template but did we check the ontology (in particular definition?)
2) size_frac_low and high will be changing, and that will need to change in the template and ontology - see https://github.com/emo-bon/governance-data/issues/21 (you will have to wait until that issue has started)

**Comment by laurianvm** [comment]
checked & no changes are needed in the ontology for the pigments and phaopigments
